variable "prefix" {
  description = "Specifies the prefix added to the names of all resources. Default is 'aws-tf'."
  type        = string
  default     = "aws-tf"
}

variable "region" {
  description = "Specifies the AWS region used for all resources. Default is 'eu-west-1'."
  type        = string
  default     = "eu-west-1"
}

variable "instance_type" {
  description = "Specifies the name of an AWS EC2 instance. Default is 'm8i.large'."
  type        = string
  default     = "m8i.large"
}

variable "create_ssh_key_pair" {
  description = "Specifies whether a new SSH key pair needs to be created for the instances. Default is 'true'."
  type        = bool
  default     = true
}

variable "ssh_private_key_path" {
  description = "Specifies the full path where the pre-generated SSH PRIVATE key is located (not generated by Terraform). Default is 'null'."
  type        = string
  default     = null
}

variable "ssh_public_key_path" {
  description = "Specifies the full path where the pre-generated SSH PUBLIC key is located (not generated by Terraform). Default is 'null'."
  type        = string
  default     = null
}

variable "ip_cidr_range" {
  description = "Specifies the range of private IPs available for the AWS Subnet. Default is '10.10.0.0/24'."
  type        = string
  default     = "10.0.0.0/16"
}

variable "spot_instance" {
  description = "Specifies whether the instances should be Spot (preemptible) VMs. Default is 'true'."
  type        = bool
  default     = true
}

variable "os_disk_size" {
  description = "Specifies the size of the disk attached to each node, in GB. Default is '50'."
  type        = number
  default     = 50
}

variable "data_disk_count" {
  description = "Specifies the number of additional data disks to attach to each VM instance. Default is 1."
  type        = number
  default     = 1
}

variable "data_disk_size" {
  description = "Specifies the size of the additional data disks for each VM instance, in GB. Default is '350'."
  type        = number
  default     = 350
}


variable "startup_script" {
  description = "Specifies a custom startup script to run when the VMs start. Default is 'null'."
  type        = string
  default     = null
}
