name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform_lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.10.5"
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check .

  gcp_terraform_plan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.10.5"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Initialize Terraform
        run: terraform init
        working-directory: projects/google-cloud/
      - name: Run Terraform Plan
        run: terraform plan
        working-directory: projects/google-cloud/

  azure_terraform_plan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.10.5"
      - name: Authenticate to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Initialize Terraform
        run: terraform init
        working-directory: projects/azure/
      - name: Run Terraform Plan
        run: terraform plan -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        working-directory: projects/azure/

  digitalocean_terraform_plan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.10.5"
      - name: Initialize Terraform
        run: terraform init
        working-directory: projects/digitalocean/
      - name: Run Terraform Plan
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
        run: terraform plan -var "do_token=$DIGITALOCEAN_TOKEN"
        working-directory: projects/digitalocean/

  aws_terraform_plan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: "1.10.5"
      - name: Authenticate to AWS Cloud
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Initialize Terraform
        run: terraform init
        working-directory: projects/aws/
      - name: Run Terraform Plan
        run: terraform plan
        working-directory: projects/aws/
