name: Test AWS VM deploy and destroy

on:
  workflow_dispatch:

jobs:
  aws_vm_terraform_deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Ensure netcat is installed
        run: sudo apt-get update && sudo apt-get install -y netcat-openbsd
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: "1.14.6"
      - name: Authenticate to AWS Cloud
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Get public IP from the GitHub Runner (security purpose)
        id: get_ip
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
          echo "Detected GitHub Runner IP: $RUNNER_IP"
      - name: Initialize Terraform
        run: terraform init
        working-directory: tests/aws/infra-only
      - name: Run Terraform apply
        run: terraform apply -var "public_ip_source_addresses=[\"$RUNNER_IP/32\"]" -auto-approve
        working-directory: tests/aws/infra-only
      - name: Get public IP from Terraform output
        id: ip
        run: |
          ip=$(terraform output -json first_instance_public_ip | jq -r '.')
          echo "INSTANCE_IP=$ip" >> $GITHUB_ENV
        working-directory: tests/aws/infra-only
      - name: Wait for SSH (port 22) to become available
        run: |
          echo "Waiting for port 22 on $INSTANCE_IP..."
          for i in {1..30}; do
            if nc -zv $INSTANCE_IP 22; then
              echo "Port 22 is open."
              exit 0
            fi
            echo "Attempt $i failed, retrying in 10s..."
            sleep 10
          done
          echo "SSH not available after 30 attempts. Failing."
          exit 1
        env:
          INSTANCE_IP: ${{ env.INSTANCE_IP }}
      - name: Run Terraform Destroy
        if: always()
        run: terraform destroy -var "public_ip_source_addresses=[\"$RUNNER_IP/32\"]" -auto-approve
        working-directory: tests/aws/infra-only
